version: '3.9'

services:
  frontend:
    container_name: demo-angular-frontend
    build:
      context: ./frontend
      args:
        - SERVICE_URL=http://host.docker.internal:5001
    ports:
      - 4200:80
    mem_limit: 64m
    cpus: 0.1
    networks:
      - order-cust-mngmnt

  backend:
    container_name: demo-angular-backend
    build:
      context: ./backend
    environment:
      - AllowedOrigins=http://host.docker.internal:4200
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=CustomerOrderManagement;User=SA;Password=Admin@123
    ports:
      - 5001:80
    mem_limit: 64m
    cpus: 0.1
    depends_on:
      - mssql
    networks:
      - order-cust-mngmnt

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@123
    volumes:
      - 'order-cust-mngmnt-data:/var/opt/mssql/data'
    mem_limit: 2.2Gb
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ""$$SA_PASSWORD"" -Q "SELECT 1" || exit 1
      timeout: 45s
      interval: 10s
      retries: 10
    cpus: 0.2
    ports:
      - 1433:1433
    networks:
      - order-cust-mngmnt

networks:
  order-cust-mngmnt:
    driver: bridge

volumes:
  order-cust-mngmnt-data:
    driver: local
